#!/usr/bin/env bash
set -Eeuo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "[dpm] config.sh must be run as root" >&2
  exit 1
fi

APP_DIR="${DPM_APP_DIR:-/opt/dimka-project-manager}"
CONFIG_DIR="${DPM_CONFIG_DIR:-/etc/dpm}"
CONFIG_FILE="${DPM_CONFIG_FILE:-$CONFIG_DIR/config.env}"
SERVICE_USER="dpm"
mkdir -p "$CONFIG_DIR"

# Load only the file generated by this script.
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

DATA_DIR="${DPM_DATA_DIR:-/var/lib/dpm}"
LOG_DIR="${DPM_LOG_DIR:-/var/log/dpm}"
RUN_DIR="/run/dpm"

SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
SERVER_IP="${SERVER_IP:-127.0.0.1}"
DEFAULT_PORT="${DPM_PORT:-8787}"
DEFAULT_BASE="${DPM_BASE_PATH:-/admin}"
DEFAULT_URL="${DPM_PUBLIC_URL:-http://${SERVER_IP}:${DEFAULT_PORT}${DEFAULT_BASE}}"
DEFAULT_USER="${DPM_ADMIN_USERNAME:-admin}"
DEFAULT_POLL="${DPM_POLL_INTERVAL:-60}"

read -r -p "Admin login [$DEFAULT_USER]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-$DEFAULT_USER}"

if [[ -n "${DPM_ADMIN_PASSWORD_HASH:-}" ]]; then
  read -r -s -p "Admin password [leave blank to keep current]: " ADMIN_PASSWORD
  echo
  if [[ -n "$ADMIN_PASSWORD" ]]; then
    PASSWORD_HASH="$("$APP_DIR/venv/bin/python" "$APP_DIR/scripts/password_hash.py" "$ADMIN_PASSWORD")"
    if [[ "$ADMIN_USER" == "admin" && "$ADMIN_PASSWORD" == "admin" ]]; then ADMIN_IS_DEFAULT=1; else ADMIN_IS_DEFAULT=0; fi
  else
    PASSWORD_HASH="$DPM_ADMIN_PASSWORD_HASH"
    ADMIN_IS_DEFAULT="${DPM_ADMIN_IS_DEFAULT:-0}"
  fi
else
  read -r -s -p "Admin password [admin]: " ADMIN_PASSWORD
  echo
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin}"
  PASSWORD_HASH="$("$APP_DIR/venv/bin/python" "$APP_DIR/scripts/password_hash.py" "$ADMIN_PASSWORD")"
  if [[ "$ADMIN_USER" == "admin" && "$ADMIN_PASSWORD" == "admin" ]]; then ADMIN_IS_DEFAULT=1; else ADMIN_IS_DEFAULT=0; fi
fi

read -r -p "Public panel URL [$DEFAULT_URL]: " PUBLIC_URL
PUBLIC_URL="${PUBLIC_URL:-$DEFAULT_URL}"
read -r -p "Listen host [${DPM_HOST:-0.0.0.0}]: " LISTEN_HOST
LISTEN_HOST="${LISTEN_HOST:-${DPM_HOST:-0.0.0.0}}"
read -r -p "Listen port [$DEFAULT_PORT]: " LISTEN_PORT
LISTEN_PORT="${LISTEN_PORT:-$DEFAULT_PORT}"
read -r -p "Base path [$DEFAULT_BASE]: " BASE_PATH
BASE_PATH="${BASE_PATH:-$DEFAULT_BASE}"
read -r -p "Git poll interval in seconds [$DEFAULT_POLL]: " POLL_INTERVAL
POLL_INTERVAL="${POLL_INTERVAL:-$DEFAULT_POLL}"

if [[ "$BASE_PATH" != /* ]]; then BASE_PATH="/$BASE_PATH"; fi
BASE_PATH="${BASE_PATH%/}"
[[ -n "$BASE_PATH" ]] || BASE_PATH="/admin"

SECRET_KEY="${DPM_SECRET_KEY:-$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
)}"
CLI_TOKEN="${DPM_CLI_TOKEN:-$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(36))
PY
)}"

quote_env() {
  local value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

cat > "$CONFIG_FILE" <<EOF_CONFIG
# Generated by Dimka Project Manager config.sh
DPM_HOST=$(quote_env "$LISTEN_HOST")
DPM_PORT=$(quote_env "$LISTEN_PORT")
DPM_BASE_PATH=$(quote_env "$BASE_PATH")
DPM_PUBLIC_URL=$(quote_env "$PUBLIC_URL")
DPM_DATA_DIR=$(quote_env "$DATA_DIR")
DPM_LOG_DIR=$(quote_env "$LOG_DIR")
DPM_POLL_INTERVAL=$(quote_env "$POLL_INTERVAL")
DPM_ADMIN_USERNAME=$(quote_env "$ADMIN_USER")
DPM_ADMIN_PASSWORD_HASH=$(quote_env "$PASSWORD_HASH")
DPM_ADMIN_IS_DEFAULT=$(quote_env "$ADMIN_IS_DEFAULT")
DPM_SECRET_KEY=$(quote_env "$SECRET_KEY")
DPM_CLI_TOKEN=$(quote_env "$CLI_TOKEN")
EOF_CONFIG

chmod 640 "$CONFIG_FILE"
chown root:"$SERVICE_USER" "$CONFIG_FILE" 2>/dev/null || true

# The daemon runs as dpm. SQLite, WAL/SHM files, repositories and logs must all
# be created and owned by that same user. Earlier versions configured the DB as
# root, which made the first write from the web panel fail with HTTP 500.
mkdir -p "$DATA_DIR/projects" "$DATA_DIR/.ssh" "$LOG_DIR" "$RUN_DIR"
chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR" "$LOG_DIR" "$RUN_DIR"

runuser -u "$SERVICE_USER" -- env \
  HOME="$DATA_DIR" \
  DPM_CONFIG_FILE="$CONFIG_FILE" \
  "$APP_DIR/venv/bin/python" "$APP_DIR/scripts/apply_admin_config.py"

# Repair ownership of an already existing database and its WAL/SHM companions.
chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR" "$LOG_DIR" "$RUN_DIR"

echo "[dpm] Configuration written to $CONFIG_FILE"
if systemctl list-unit-files dimka-project-manager.service >/dev/null 2>&1; then
  systemctl restart dimka-project-manager.service || true
  echo "[dpm] Service restarted"
fi
echo "[dpm] Panel: $PUBLIC_URL"
